// <auto-generated/>
using global::System;
using global::System.Drawing;
using global::System.IO;
using global::System.Threading.Tasks;
using global::System.Windows.Forms;


namespace Martinez_Pad
{
	internal static class Program
	{
		/// <summary>
		///  The main entry point for the application.
		/// </summary>
		[STAThread]
		static void Main()
		{
			// To customize application configuration such as set high DPI settings or default font,
			// see https://aka.ms/applicationconfiguration.
			Application.EnableVisualStyles();
			Application.SetCompatibleTextRenderingDefault(false);
			Application.Run(new Form1());
		}
	}
}